apiVersion: apps/v1
kind: Deployment
metadata: 
   name: golang
   labels:
     app: golang-app
     version: golang-version
spec: 
   replicas: {{ .Values.replicaCount }}
   selector:
     matchLabels:
       app: golang-app
       version: golang-version
   template:
      metadata:
       name: golang 
       labels:
         app: golang-app
         version: golang-version
      spec:
        containers: 
        - name: {{ .Chart.Name }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: 
            requests: 
              memory: "64Mi"
              cpu: "250m"
            limits: 
              memory: "64Mi"
              cpu: "250m"
          ports:
          - containerPort: 8010
          volumeMounts:
          - name: {{ .Values.volume.name }}"
            mountPath: {{ .Values.volume.path }}"
        volumes:
        - name: {{ .Values.volume.name }}"
          persistentVolumeClaim:
            claimName: {{ .Values.volume.claimName }}"


