apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
 annotations: 
   cert-manager.io/cluster-issuer: letsencrypt-prod 
 name: {{ .Values.ingress.name }}
spec: 
   ingressClassName: nginx
   rules:
     - host: {{ .Values.ingress.host }}
       http: 
        paths:
         - backend:
            service:
              name: golang
              port:
               number: {{ .Values.service.port }}
           path:  /
           pathType:  ImplementationSpecific
   tls:
     - hosts:
         - {{ .Values.ingress.host }}
       secretName: selimzakhama-nginx-tls



