apiVersion: v1
kind: Service
metadata: 
   name: {{ .Values.service.name }}
spec: 
   selector:
     app: golang-app
     version: golang-version
   ports:
   - protocol: {{ .Values.service.protocol | default "TCP" }}
     port: {{ .Values.service.port }}
